### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pakdev** [estruyf/vscode-auth-sample#1]
Hello, thanks for the helpful sample code (and website explaining it)! I'd like to adapt some of this code for use in my project, but I'm not sure what the license is. Do you mind adding one? Thanks!

**Comment by estruyf** [comment]
I'll add the MIT license to it, so feel free to use it in any way you want.

**Comment by estruyf** [comment]
There we go, added the license.

**Comment by pakdev** [comment]
Awesome, I appreciate it!
